In [1]:
import pandas as pd
import numpy as np
import time
import datetime 
import scipy.stats
from matplotlib import pyplot as plt
import seaborn as sns
pd.options.display.max_rows = 53000

In [2]:
gender = pd.read_csv('/mnt/c/users/marcj/Desktop/Data Science/titanic/Titanic/Data/gender_submission.csv')

In [3]:
gender.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [4]:
gender.describe()

       PassengerId    Survived
count   418.000000  418.000000
mean   1100.500000    0.363636
std     120.810458    0.481622
min     892.000000    0.000000
25%     996.250000    0.000000
50%    1100.500000    0.000000
75%    1204.750000    1.000000
max    1309.000000    1.000000

In [5]:
gender

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
5            897         0
6            898         1
7            899         0
8            900         1
9            901         0
10           902         0
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         1
19           911         1
20           912         0
21           913         0
22           914         1
23           915         0
24           916         1
25           917         0
26           918         1
27           919         0
28           920         0
29           921         0
30           922         0
31           923         0
32           924         1
33           925         1
34           926         0
35           927         0
36           928         1
37           929         1
38           930         0
39           931         0
40           932         0
41           933         0
42           934         0
43           935         1
44           936         1
45           937         0
46           938         0
47           939         0
48           940         1
49           941         1
50           942         0
51           943         0
52           944         1
53           945         1
54           946         0
55           947         0
56           948         0
57           949         0
58           950         0
59           951         1
60           952         0
61           953         0
62           954         0
63           955         1
64           956         0
65           957         1
66           958         1
67           959         0
68           960         0
69           961         1
70           962         1
71           963         0
72           964         1
73           965         0
74           966         1
75           967         0
76           968         0
77           969         1
78           970         0
79           971         1
80           972         0
81           973         0
82           974         0
83           975         0
84           976         0
85           977         0
86           978         1
87           979         1
88           980         1
89           981         0
90           982         1
91           983         0
92           984         1
93           985         0
94           986         0
95           987         0
96           988         1
97           989         0
98           990         1
99           991         0
100          992         1
101          993         0
102          994         0
103          995         0
104          996         1
105          997         0
106          998         0
107          999         0
108         1000         0
109         1001         0
110         1002         0
111         1003         1
112         1004         1
113         1005         1
114         1006         1
115         1007         0
116         1008         0
117         1009         1
118         1010         0
119         1011         1
120         1012         1
121         1013         0
122         1014         1
123         1015         0
124         1016         0
125         1017         1
126         1018         0
127         1019         1
128         1020         0
129         1021         0
130         1022         0
131         1023         0
132         1024         1
133         1025         0
134         1026         0
135         1027         0
136         1028         0
137         1029         0
138         1030         1
139         1031         0
140         1032         1
141         1033         1
142         1034         0
143         1035         0
144         1036         0
145         1037         0
146         1038         0
147         1039         0
148         1040         0
149         1041         0
150         1042         1
151         1043         0
152         1044         0
153         1045         1
154         1046         0
155         1047         0
156         1048         1
157         1049         1
158         1050         0
159         1051         1
160         1052         1
161         1053         0
162         1054         1
163         1055         0
164         1056         0
165         1057         1
166         1058         0
167         1059         0
168         1060         1
169         1061         1
170         1062         0
171         1063         0
172         1064         0
173         1065         0
174         1066         0
175         1067         1
176         1068         1
177         1069         0
178         1070         1
179         1071         1
180         1072         0
181         1073         0
182         1074         1
183         1075         0
184         1076         1
185         1077         0
186         1078         1
187         1079         0
188         1080         1
189         1081         0
190         1082         0
191         1083         0
192         1084         0
193         1085         0
194         1086         0
195         1087         0
196         1088         0
197         1089         1
198         1090         0
199         1091         1
200         1092         1
201         1093         0
202         1094         0
203         1095         1
204         1096         0
205         1097         0
206         1098         1
207         1099         0
208         1100         1
209         1101         0
210         1102         0
211         1103         0
212         1104         0
213         1105         1
214         1106         1
215         1107         0
216         1108         1
217         1109         0
218         1110         1
219         1111         0
220         1112         1
221         1113         0
222         1114         1
223         1115         0
224         1116         1
225         1117         1
226         1118         0
227         1119         1
228         1120         0
229         1121         0
230         1122         0
231         1123         1
232         1124         0
233         1125         0
234         1126         0
235         1127         0
236         1128         0
237         1129         0
238         1130         1
239         1131         1
240         1132         1
241         1133         1
242         1134         0
243         1135         0
244         1136         0
245         1137         0
246         1138         1
247         1139         0
248         1140         1
249         1141         1
250         1142         1
251         1143         0
252         1144         0
253         1145         0
254         1146         0
255         1147         0
256         1148         0
257         1149         0
258         1150         1
259         1151         0
260         1152         0
261         1153         0
262         1154         1
263         1155         1
264         1156         0
265         1157         0
266         1158         0
267         1159         0
268         1160         1
269         1161         0
270         1162         0
271         1163         0
272         1164         1
273         1165         1
274         1166         0
275         1167         1
276         1168         0
277         1169         0
278         1170         0
279         1171         0
280         1172         1
281         1173         0
282         1174         1
283         1175         1
284         1176         1
285         1177         0
286         1178         0
287         1179         0
288         1180         0
289         1181         0
290         1182         0
291         1183         1
292         1184         0
293         1185         0
294         1186         0
295         1187         0
296         1188         1
297         1189         0
298         1190         0
299         1191         0
300         1192         0
301         1193         0
302         1194         0
303         1195         0
304         1196         1
305         1197         1
306         1198         0
307         1199         0
308         1200         0
309         1201         1
310         1202         0
311         1203         0
312         1204         0
313         1205         1
314         1206         1
315         1207         1
316         1208         0
317         1209         0
318         1210         0
319         1211         0
320         1212         0
321         1213         0
322         1214         0
323         1215         0
324         1216         1
325         1217         0
326         1218         1
327         1219         0
328         1220         0
329         1221         0
330         1222         1
331         1223         0
332         1224         0
333         1225         1
334         1226         0
335         1227         0
336         1228         0
337         1229         0
338         1230         0
339         1231         0
340         1232         0
341         1233         0
342         1234         0
343         1235         1
344         1236         0
345         1237         1
346         1238         0
347         1239         1
348         1240         0
349         1241         1
350         1242         1
351         1243         0
352         1244         0
353         1245         0
354         1246         1
355         1247         0
356         1248         1
357         1249         0
358         1250         0
359         1251         1
360         1252         0
361         1253         1
362         1254         1
363         1255         0
364         1256         1
365         1257         1
366         1258         0
367         1259         1
368         1260         1
369         1261         0
370         1262         0
371         1263         1
372         1264         0
373         1265         0
374         1266         1
375         1267         1
376         1268         1
377         1269         0
378         1270         0
379         1271         0
380         1272         0
381         1273         0
382         1274         1
383         1275         1
384         1276         0
385         1277         1
386         1278         0
387         1279         0
388         1280         0
389         1281         0
390         1282         0
391         1283         1
392         1284         0
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         0
404         1296         0
405         1297         0
406         1298         0
407         1299         0
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         1
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

In [7]:
train_data = pd.read_csv('/mnt/c/users/marcj/Desktop/Data Science/titanic/Titanic/Data/train.csv')

In [9]:
train_data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [10]:
train_data.head(20)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C

In [11]:
train_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')